name: CI
on:
  pull_request:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18' ]
    name: Run vet (Go ${{ matrix.go }})
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Run linters
        run: make lint
      - name: Run tests
        run: make test
